In [1]:
import gym
import numpy as np
import random

from IPython.display import clear_output
from time import sleep

In [2]:
env = gym.make("FrozenLake8x8-v0")
action = env.reset()

In [3]:
print(env.action_space.n)
print(env.observation_space.n)

4
64


In [4]:

env.render()
state_t, reward, done, e = env.step(env.action_space.sample())
print(reward)
if done:
    env.reset()
    print(reward, "dsds")


SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG
0.0


In [5]:
qtable = np.zeros((64, 4))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# 파라메터 설정
total_episodes = 100000 # 총 에피소드 수
total_test_episodes = 100 # 총 테스트 에피소드
max_steps = 100 # 하나의 에피소드에서 최대로 움직일 수 있는 수

learning_rate = 0.3 # 학습률
gamma = 0.8 # 미래 지향적일지 아닐지 선택, 크면 클수록 근시안적임

#탐색 파라메터
epsilon = 1.0 # 탐색률
max_epsilon = 1.0 # 탐색 나갈 최대의 확률
min_epsilon = 0.01 # 탐색 나갈 최소의 확률
decay_rate = 0.0001 # 점점 탐색 확률을 줄여나갈 크기

rewards = 0

In [7]:
# 원래는 러닝 구간이지만,
# 이미 러닝된 것을 불러온다.

qtable = np.load('C:/SB/reinforcement/notebook/notebooks.npy')
        

In [8]:
print(qtable)
print(rewards)

[[8.18535488e-05 7.89746743e-05 2.24034964e-04 9.70369974e-05]
 [1.62850915e-04 3.56723291e-05 4.79621020e-04 1.61485714e-04]
 [9.10331850e-05 2.93093565e-04 1.13535652e-03 1.25941783e-04]
 [2.32298764e-04 2.65787416e-04 1.75795958e-03 4.79633952e-04]
 [4.34405699e-04 6.43640061e-04 2.45225224e-03 7.01525846e-04]
 [1.24654450e-03 1.61599308e-03 3.33062834e-03 1.02428058e-03]
 [3.52378104e-03 1.91224048e-03 5.25339494e-03 8.86165517e-04]
 [2.26831472e-03 9.12786830e-03 2.18948271e-03 1.70091420e-03]
 [6.98693398e-05 6.16823590e-05 6.00676744e-05 1.88526303e-04]
 [1.17957668e-04 8.77231705e-05 2.20821341e-04 8.10974310e-05]
 [1.41317486e-04 1.24928182e-04 8.66665277e-04 9.53853766e-05]
 [1.89951453e-04 2.41464757e-04 2.10754519e-04 1.45742642e-03]
 [6.61494964e-04 1.11716787e-03 2.58073118e-03 5.67966739e-04]
 [9.75455398e-04 1.13914446e-03 4.87636528e-03 1.06531372e-03]
 [2.40448432e-03 3.31137880e-03 1.08886020e-02 3.44981158e-03]
 [4.08590518e-03 2.40569125e-02 2.04395745e-03 3.898936

In [10]:
show = 0
for i in range(100):
    state = env.reset()
    for step in range(50):
        clear_output()
        env.render()
        sleep(0.5)
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, _ = env.step(action)
        
        state = new_state
        
        if done == True:
            if reward == 1:
                show += reward
            sleep(0.5)
            clear_output()
            env.render()
            sleep(0.5)
            break
        print(show)

  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG


KeyboardInterrupt: 

In [ ]:
print(rewards / total_episodes)